#include <ansi.h>
#include <task.h>

// 数组：标准提示信息 -- [随意]
mapping TipsTable = ([
             "Hoa Tượng" :   "Loại hoa này có khá nhiều ở "HIR"khúc cua của trang viện nhà Đường"NOR", nhưng nơi đó khá nguy hiểm.",
             "Cây lan" :   ""HIR"Trang viện nhà Đường"NOR" đều có trồng Cây lan, bạn đến đó tìm kiếm chắc sẽ có thu hoạch.",
             "Măng tây" :   "Đây là một loại thực vật khá hiếm... nhưng nghe nói "HIR"nữ sát thủ"NOR" đều thích đeo loại thực vật này làm bùa hộ mệnh.",
             "Cây cúc" :   "Loại hoa này có khắp nơi, trên "HIR"núi Thủ Dương"NOR" có rất nhiều.",
             "Hoa hồng" :   "Những "HIR"công tử bột"NOR" suốt ngày lêu lổng đều rất thích đeo loại hoa này trên người, bạn có thể thử tìm họ xin.",
             "Hoa nhài" :   "Loại hoa này ở vùng "HIR"Trường Bạch Sơn"NOR" chắc sẽ có nhiều chứ?",
             "Cây mẫu đơn" :   "Loại hoa này ở vùng "HIR"Trường Bạch Sơn"NOR" chắc sẽ có nhiều chứ?",
             "Hoa đào" :   "Ở "HIR"làng Đào Nguyên"NOR" khắp núi đồi đều nở đầy loại hoa tươi này.",
             "Hoa trà" :   "Loại hoa này ở vùng "HIR"Trường Bạch Sơn"NOR" chắc sẽ có nhiều chứ?",
             "Hoa mẫu đơn" :   "Hoa mẫu đơn có vẻ như có thể tìm thấy ở vùng "HIR"Vân Mộng Trạch"NOR".",
             "Hoa bìm bìm" :   "Hoa bìm bìm có vẻ như có thể tìm thấy ở vùng "HIR"Vân Mộng Trạch"NOR".",
             "Hoa dâm bụt" :   "Đến vùng "HIR"Triều Dương Phong"NOR" hoặc "HIR"Hoa Sơn"NOR" tìm kiếm xem, chắc sẽ phát hiện được.",
             "Hoa thủy tiên" :   "Bạn đến vùng "HIR"Động Đình Hồ"NOR" tìm kiếm xem, chắc sẽ phát hiện được.",
             "Thu hải đường" :   "Loại hoa này có vẻ như mọc ở vùng "HIR"Cửu Khúc Kiều"NOR" chứ?",
             "Hoa huệ" :   "Loại hoa này có vẻ như mọc ở vùng "HIR"Trường Bạch Sơn"NOR" chứ?",
             "Tử đinh hương" :   "Đến vùng "HIR"Thúy Hoa Sơn"NOR" hoặc "HIR"Thủ Dương Sơn"NOR" xem xem, chắc sẽ có.",
             "Trà Đen" :   "Nghe nói một số "HIR"yêu quái báo hoa"NOR" thích mang loại trà này trên người.",
             "Trà Xanh" :   "Nghe nói một số "HIR"yêu quái báo hoa"NOR" thích mang loại trà này trên người.",
             "Trà Jasmine" :   ""HIR"Binh sĩ nước Yên"NOR" đều rất thích uống loại trà này, bạn đến "HIR"Vạn Lý Trường Thành nước Yên"NOR" xin họ thế nào?",
             "Trà Pu'er" :   ""HIR"Binh sĩ nước Yên"NOR" đều rất thích uống loại trà này, bạn đến "HIR"Vạn Lý Trường Thành nước Yên"NOR" xin họ thế nào?",
             "Trà Quan Vũ" :   "Binh sĩ nước Sở đều rất thích uống loại trà này, bạn đến "HIR"Phương Thành nước Sở"NOR" xin họ thế nào?",
             "Longjing trà" :   "Nghe nói "HIR"chó rừng"NOR" đang tu luyện rất thích uống Longjing trà, bạn có thể đi tìm xem.",
             "trà Mist" :   "Binh sĩ nước Sở đều rất thích uống loại trà này, bạn đến "HIR"Phương Thành nước Sở"NOR" xin họ thế nào?",
             "Lá Trà Quan Vũ" :   "Binh sĩ nước Sở đều rất thích uống loại trà này, bạn đến "HIR"Phương Thành nước Sở"NOR" xin họ thế nào?",
             "Trà mây" :   "Binh sĩ nước Sở đều rất thích uống loại trà này, bạn đến "HIR"Phương Thành nước Sở"NOR" xin họ thế nào?",
             "Rượu gạo" :   ""HIR"Binh sĩ nước Triệu"NOR" và "HIR"nước Sở"NOR" đều khá thích uống loại rượu này.",
             "Hoàng Tửu" :   ""HIR"Binh sĩ nước Tần"NOR" và "HIR"nước Sở"NOR" đều khá thích uống loại rượu này.",
             "Lão Tửu" :   ""HIR"Binh sĩ nước Tần"NOR" và "HIR"nước Sở"NOR" đều khá thích uống loại rượu này.",
             "Hỏa Đao Tửu" :   ""HIR"Bọn cướp và du côn"NOR" ở vùng "HIR"sông Vô Định"NOR" đều rất thích uống loại rượu này.",
             "Đầm Lầy" :   "Rượu này ở vùng "HIR"Vạn Lý Trường Thành nước Triệu"NOR" chắc sẽ tìm thấy được.",
             "Rượu Dukang" :   ""HIR"Bọn cướp"NOR" ở vùng "HIR"Ải Nhạn Môn"NOR" có vẻ như đều uống loại rượu này.",
             "Rượu vang đỏ" :   ""HIR"Bọn cướp"NOR" ở vùng "HIR"Ải Nhạn Môn"NOR" có vẻ như đều uống loại rượu này.",
             "Lúa nước" :   ""HIR"Gà con"NOR" trên người có chứ?",
             "Lúa mì" :   ""HIR"Gà con"NOR" trên người có chứ?",
             "Ngô" :   ""HIR"Gà con"NOR" trên người có chứ?",
             "Kê" :   ""HIR"Gà con"NOR" trên người có chứ?",
             "Cao lương" :   "Tôi nhớ ở "HIR"Vân Mộng Trạch"NOR" có thể tìm thấy cao lương.",
             "Bí đao" :   "Bí đao và bí ngô đều là thức ăn mà "HIR"lợn rừng"NOR" thích ăn.",
             "Bí ngô" :   "Bí đao và bí ngô đều là thức ăn mà "HIR"lợn rừng"NOR" thích ăn.",
             "Dưa chuột" :   "Dưa chuột trên người "HIR"quái vật đầu bò"NOR" chắc sẽ tìm thấy được.",
             "Củ cải" :   "Bạn đi hỏi "HIR"thỏ"NOR" xin đi.",
             "Cải thảo" :   "Bạn đi hỏi "HIR"thỏ"NOR" xin đi.",
             "Rau xanh" :   "Bạn đi hỏi "HIR"thỏ"NOR" xin đi.",
             "Khoai lang" :   "Binh sĩ nước Sở có vẻ như đều mang "HIR"khoai lang"NOR" trên người làm lương khô.",
             "Hoài sơn" :   "Tôi nhớ ở vùng "HIR"Hoa Sơn"NOR" có thể tìm thấy...",
             "Củ sen" :   "Bạn đến "HIR"bờ biển Đông Hải"NOR" tìm kiếm xem, chắc sẽ phát hiện được nhiều.",
             "Cà tím" :   "Có vẻ như vùng "HIR"làng Đào Nguyên"NOR" có khá nhiều.",
             "Măng tre" :   "Vùng "HIR"Trường Bạch Sơn"NOR" mọc khá nhiều măng tre chứ?",
             "Nấm" :   ""HIR"Thỏ con"NOR" đều thích ăn nấm.",
             "Đậu xanh" :   ""HIR"Kiến"NOR" đều thích thu thập những hạt đậu này.",
             "Đậu nành" :   ""HIR"Kiến"NOR" đều thích thu thập những hạt đậu này.",
             "Đậu dẹt" :   ""HIR"Kiến"NOR" đều thích thu thập những hạt đậu này.",
             "Đậu phộng" :   ""HIR"Kiến"NOR" đều thích thu thập những hạt đậu này.",
             "Mè" :   ""HIR"Kiến"NOR" đều thích thu thập những hạt đậu này.",
             "Hạt cải dầu" :   "Tôi nhớ trên người "HIR"nhện"NOR" đôi khi sẽ dính một số hạt cải dầu.",
             "Ớt" :   "Bạn có ăn được cay không? Tôi biết người "HIR"nước Triệu"NOR" khá ăn được cay.",
             "Hành lá" :   ""HIR"Binh sĩ nhỏ nước Yên"NOR" có vẻ như rất thích mùi vị hành lá.",
             "Tỏi" :   "Tôi nghĩ ở "HIR"gần núi Thái"NOR" có thể tìm thấy tỏi.",
             "Gừng" :   "Ở "HIR"gần núi Đại Biệt"NOR" hoặc có thể tìm thấy cũng không chừng.",
             "Mật ong" :   "Tổ "HIR"ong mật"NOR" có rất nhiều.",
             "Thuốc lá" :   ""HIR"Chó điên"NOR" ở "HIR"Triều Dương Phong"NOR" rất thích ngậm thuốc lá chạy lung tung.",
             "Trứng gà" :   "Trang trại nuôi "HIR"gà"NOR" có khá nhiều.",
             "Trứng vịt" :   "Vùng "HIR"Đông Hải"NOR" chắc có khá nhiều chứ?",
             "Trứng chim" :   "Trang trại nuôi "HIR"gà"NOR" có khá nhiều.",
             "Trứng rùa" :   "Vùng "HIR"Đông Hải"NOR" chắc có khá nhiều chứ?",
             "Dưa hấu" :   ""HIR"Lợn rừng"NOR" đều rất thích ăn Dưa hấu.",
             "Chuối" :   ""HIR"Khỉ"NOR" đều rất thích ăn Chuối chứ? Bạn đến nơi "HIR"khỉ"NOR" tụ tập tìm là được.",
             "Trái quýt" :   "Tôi nghĩ bạn nên đến "HIR"Thái Hồ"NOR" tìm kiếm xem.",
             "Trái Táo" :   ""HIR"Khỉ"NOR" đều rất thích ăn Trái Táo chứ? Bạn đến nơi "HIR"khỉ"NOR" tụ tập tìm là được.",
             "Trái lê" :   "Trên "HIR"núi Thái"NOR" có khá nhiều Trái lê.",
             "Đào" :   ""HIR"Khỉ"NOR" đều rất thích ăn Đào chứ? Bạn đến nơi "HIR"khỉ"NOR" tụ tập tìm là được.",
             "Cây nguyệt quế" :   "Tôi nghĩ... có lẽ ở vùng "HIR"Xích Bích"NOR" có thể tìm thấy Cây nguyệt quế.",
             "Quả nho" :   ""HIR"Vân Mộng Trạch"NOR" có Quả nho.",
             "Nhãn" :   "Tôi nghĩ "HIR"Hoa Sơn"NOR" hoặc Triều Dương Phong sẽ có khá nhiều.",
             "Vải thiều" :   "Vùng "HIR"Động Đình Hồ"NOR" có khá nhiều Vải thiều.",
             "bánh quy" :   "Tôi nhớ "HIR"quái vật đầu bò"NOR" sẽ mang bánh quy trên người làm lương khô.",
             "bánh kếp" :   "Tôi tin những "HIR"du côn"NOR" sẽ mang bánh kếp trên người.",
             "Bánh đậu đỏ" :   "Nghe nói một số "HIR"trộm cắp"NOR" khá thích loại đồ ăn vặt này.",
             "Bánh đậu" :   "Nghe nói một số "HIR"chó rừng"NOR" khá thích loại đồ ăn vặt này.",
             "thịt bò khô" :   "Tôi nghĩ một số "HIR"quái vật đầu bò"NOR" chắc sẽ mang thịt bò khô trên người...",
             "thịt nướng kebab" :   "Tôi nghĩ một số "HIR"quái vật đầu bò"NOR" chắc sẽ mang thịt nướng kebab trên người...",
             "Khoai Lang Nướng" :   "Tôi nhớ tôi từng ăn loại đồ ăn vặt này ở vùng "HIR"Đông Hải"NOR".",
             "Đậu phụ khô" :   "Tôi nhớ tôi từng ăn loại đồ ăn vặt này ở vùng "HIR"Quế Lăng"NOR".",
             "Đậu phụ thối" :   "Những người lao động khổ sai ở "HIR"kênh Trịnh Quốc"NOR" thường ăn những thứ này.",
             "Hạt dưa chiên" :   "Những người lao động khổ sai ở "HIR"kênh Trịnh Quốc"NOR" thường ăn những thứ này.",
             "Đậu phộng chiên" :   "Những người lao động khổ sai ở "HIR"kênh Trịnh Quốc"NOR" thường ăn những thứ này.",
             "Kẹo Hồ Lô" :   "Tôi nhớ ở Bạch Mã Trang từng ăn loại đồ ăn vặt này.",
             "铁铲" :   "Công cụ này chắc nên đến vùng "HIR"kênh Trịnh Quốc"NOR" tìm chứ?",
             "锄头" :   "Công cụ này chắc nên đến vùng "HIR"kênh Trịnh Quốc"NOR" tìm chứ?",
             "铁犁" :   "Công cụ này chắc nên đến vùng "HIR"kênh Trịnh Quốc"NOR" tìm chứ?",
             "镰刀" :   "Tiêu diệt những "HIR"quái vật bọ ngựa"NOR" có thể sẽ được một cái liềm.",
             "钉耙" :   "Một số "HIR"quái vật đầu bò"NOR" sẽ dùng cào sắt làm vũ khí của mình.",
             "草叉" :   "Một số "HIR"quái vật đầu bò"NOR" sẽ dùng chĩa cỏ làm vũ khí của mình.",
             "铁锤" :   "Công cụ này chắc nên đến vùng "HIR"kênh Trịnh Quốc"NOR" tìm chứ?",
             "木槌" :   "Công cụ này chắc nên đến vùng "HIR"kênh Trịnh Quốc"NOR" tìm chứ?",
             "凿子" :   "Công cụ này chắc nên đến vùng "HIR"kênh Trịnh Quốc"NOR" tìm chứ?",
             "刨子" :   "Công cụ này chắc nên đến vùng "HIR"kênh Trịnh Quốc"NOR" tìm chứ?",
             "锯子" :   "Công cụ này chắc nên đến vùng "HIR"kênh Trịnh Quốc"NOR" tìm chứ?",
             "簸箕" :   "Công cụ này chắc nên đến vùng "HIR"kênh Trịnh Quốc"NOR" tìm chứ?",
             "小木桶" :   "Tôi nhớ thứ này "HIR"quái vật đầu bò"NOR" trên người sẽ có...",
             "柱香" :   "Tôi nghĩ trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" sẽ có khá nhiều những thứ này.",
             "蜡烛" :   "Tôi nghĩ trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" sẽ có khá nhiều những thứ này.",
             "檀香" :   "Tôi nghĩ trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" sẽ có khá nhiều những thứ này.",
             "黄纸" :   "Tôi nghĩ trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" sẽ có khá nhiều những thứ này.",
             "纸钱" :   "Tôi nghĩ trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" sẽ có khá nhiều những thứ này.",
             "朱砂" :   "Tôi nghĩ trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" sẽ có khá nhiều những thứ này.",
             "法笔" :   "Tôi nghĩ trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" sẽ có khá nhiều những thứ này.",
             "小香炉" :   "Tôi nghĩ trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" sẽ có khá nhiều những thứ này.",
             "鹤嘴炉" :   "Tôi nghĩ trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" sẽ có khá nhiều những thứ này.",
             "铁锅" :   "Tiêu diệt những "HIR"Ác ma trong lọ"NOR" có thể sẽ có một cái nồi sắt rơi ra cũng không chừng.",
             "陶碗" :   "Đánh bại những "HIR"chó rừng"NOR" có thể sẽ có một cái bát sứ rơi ra cũng không chừng.",
             "金碗" :   "Truyền thuyết "HIR"Ác ma trong lọ"NOR" sở hữu một cái bát vàng, không biết thật giả thế nào.",
             "竹筷" :   "Ở gần "HIR"làng mới"NOR" có thể tìm thấy chứ?",
             "银筷" :   "Nghe nói một số "HIR"kẻ cuồng"NOR" sẽ giấu đũa bạc cướp được từ người khác trên người mình.",
             "碟子" :   ""HIR"Người lao động khổ sai"NOR" ở "HIR"kênh Trịnh Quốc"NOR" chắc đều mang theo chứ?",
             "盘子" :   ""HIR"Người lao động khổ sai"NOR" ở "HIR"kênh Trịnh Quốc"NOR" chắc đều mang theo chứ?",
             "勺子" :   ""HIR"Người lao động khổ sai"NOR" ở "HIR"kênh Trịnh Quốc"NOR" chắc đều mang theo chứ?",
             "水瓢" :   "Tôi nghĩ trên người "HIR"tôm binh"NOR" sẽ mang theo gáo nước.",
             "菜刀" :   "Những "HIR"kẻ xấu"NOR" chắc mang theo một con dao thái chứ?",
             "剪刀" :   "Tiêu diệt một con "HIR"quái vật bọ ngựa"NOR" thử xem, có thể sẽ có kéo rơi ra.",
             "茶壶" :   "Tôi nghĩ chắc trên người "HIR"trộm cắp"NOR" có thể lấy được ấm trà.",
             "打火石" :   "Bạn đến trong "HIR"Linh Cốc Động"NOR" chắc có thể tìm thấy đá lửa.",
             "胭脂" :   "Những công tử bột ("HIR"du côn"NOR") suốt ngày mang phấn son trên người, làm cho mình thành một dáng vẻ kỳ quái không nam không nữ.",
             "水粉" :   "Những công tử bột ("HIR"du côn"NOR") suốt ngày mang phấn son trên người, làm cho mình thành một dáng vẻ kỳ quái không nam không nữ.",
             "敷面粉" :   "Tôi nghĩ những thứ này có thể sẽ được đặt làm đồ tùy táng trong "HIR"Linh Cốc Động"NOR" chứ?",
             "红印纸" :   "Tôi nghĩ những thứ này có thể sẽ được đặt làm đồ tùy táng trong "HIR"Linh Cốc Động"NOR" chứ?",
             "发刷" :   "Tôi nghĩ những thứ này có thể sẽ được đặt làm đồ tùy táng trong "HIR"Linh Cốc Động"NOR" chứ?",
             "粉扑" :   "Bạn có để ý mặt đỏ ửng của những "HIR"quái vật lợn rừng"NOR" không? Chắc là do đánh phấn.",
             "发夹" :   "Tôi nhớ từng thấy một số yêu quái mang thứ này ở "HIR"Trường Bạch Sơn"NOR"...",
             "铜镜" :   "Trong "HIR"Linh Cốc Động"NOR" chắc có rất nhiều gương đồng.",
             "手镜" :   "Tôi nhớ từng thấy một số yêu quái mang thứ này ở "HIR"Trường Bạch Sơn"NOR"...",
             "锣" :   "Một số "HIR"yêu quái sói"NOR" mang theo chiêng.",
             "鼓" :   "Một số "HIR"yêu quái hổ"NOR" sẽ mang theo trống.",
             "钹" :   ""HIR"Yêu quái lợn rừng"NOR" có thể mang theo chũm chọe.",
             "梆子" :   ""HIR"Bọn cướp"NOR" cũng thích chơi một chút mõ để tự giải trí.",
             "笛子" :   ""HIR"Binh sĩ nước Tần"NOR" cũng thích thổi một chút sáo để giải trí.",
             "唢呐" :   ""HIR"Yêu quái lợn rừng"NOR" có thể mang theo kèn.",
             "萧" :   ""HIR"Binh sĩ nước Tần"NOR" thích nghịch nhạc cụ để giải trí.",
             "竽" :   ""HIR"Binh sĩ nước Tần"NOR" thích nghịch nhạc cụ để giải trí.",
             "筝" :   ""HIR"Binh sĩ nước Tần"NOR" thích nghịch nhạc cụ để giải trí.",
             "琵琶" :   "Tôi nghĩ loại nhạc cụ này ở "HIR"Đông Hải"NOR" có thể sẽ tìm thấy.",
             "Đàn nhị" :   ""HIR"Người nước Yên"NOR" đều thích kéo Đàn nhị.",
             ""一筒"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""二筒"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""三筒"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""四筒"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""五筒"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""六筒"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""七筒"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""八筒"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""九筒"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""一条"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""二条"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""三条"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""四条"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""五条"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""六条"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""七条"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""八条"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""九条"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""一万"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""二万"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""三万"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""四万"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""五万"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""六万"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""七万"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""八万"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""九万"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""东风"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""南风"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""西风"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""北风"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""红中"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""发财"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""白板"" :   "Những "HIR"kẻ xấu"NOR" ham mê cờ bạc như mạng sống trên người chắc sẽ có!",
             ""帅"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""仕"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""相"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""車"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""馬"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""炮"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""兵"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""将"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""士"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""象"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""车"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""马"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""砲"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             ""卒"" :   "Tôi nghĩ ở vùng "HIR"Vạn Lý Trường Thành nước Yên, Triệu, Tần"NOR" có thể phát hiện được khá nhiều quân cờ.",
             "黑棋子" :   "Tôi nhớ trong "HIR"mộ cổ tướng quân"NOR" sẽ có.",
             "白棋子" :   "Tôi nhớ trong "HIR"mộ cổ tướng quân"NOR" sẽ có.",
             "竹子" :   ""HIR"Bù nhìn rơm"NOR" trên người có rất nhiều chứ?",
             "竹蜻蜓" :   "Những con "HIR"khỉ"NOR" xấu nghịch ngợm thường xuyên ăn cắp đồ chơi của trẻ con.",
             "小风车" :   "Những "HIR"người sói"NOR" đáng ghét thường xuyên ăn cắp đồ chơi của trẻ con.",
             "小泥人" :   "Một số "HIR"thảo khấu"NOR" thường xuyên dùng một số con người đất sét để lừa trẻ con.",
             "泥块" :   ""HIR"Bù nhìn rơm"NOR" trên người có rất nhiều chứ?",
             "冰块" :   "Vùng "HIR"Đông Hải"NOR" chắc có thể tìm thấy đá lạnh chứ?",
             "Điêu khắc刀" :   ""HIR"Sư tử đá"NOR" và "HIR"hổ đá"NOR" trong cơ thể chắc sẽ giấu một con dao khắc.",
             "柳条" :   "Tôi nhớ ở "HIR"khúc cua trang viện nhà Đường"NOR" có thể tìm thấy cành liễu.",
             "木板" :   "Ván gỗ chắc ở vùng "HIR"kênh Trịnh Quốc"NOR" có khá nhiều chứ?",
             "玉石" :   ""HIR"Sư tử đá và hổ đá"NOR" trong cơ thể chắc đều giấu một viên ngọc làm nguồn động lực.",
]);
//变身卡
static string *nCard = ({"0010","0011","0050","0051","0052","0053","0101","0102","0150",
			"0151","0152","0200","0201","0202","0250","0251","0252","8011",
			"8010","0300","0301","0302","0303","0304","0350","0351","0352",
			"0400","0401","0402","0450","0500","0502","0550","0551","0552",
		});
		
// 函数：显示提示信息(场景公用)
string get_gift_tips( string id )
{
        return TipsTable[id];
}
//获得随机变身卡
string get_random_card()
{
	return "item/54/"+nCard[random(sizeof(nCard))];
}
